import React from 'react'

const contact = () => {
  return (
    <div>
file based routing 2
    </div>
  )
}

export default contact

export const metadata = {                       //can change dec and title according to the routes
  title: "CONTACT PAGE",
  description: "Generated by create next app",
};