// LAYOUTS
//IF we want to add specific component in all pages with endpoints admin routes like localhost/admin/login or localhost/admin/logout

import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar.jsx";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <>
        <span>Admin Navbar</span>
        <Navbar/>
        {children}
        </>

    );
}
