import React from 'react'

const page = () => {
  return (
    <div>LOGIN</div>
  )
}

export default page

export const metadata = {
    title: "LOGIN PAGE",
    description: "Generated by create next app",
};