import React from 'react'

const page = () => {
  return (
    <div>LOGOUT</div>
  )
}

export default page

export const metadata = {
    title: "LOGOUT PAGE",
    description: "Generated by create next app",
};
