
import React from 'react'

const about = () => {
  return (
    <div>
      About Page
    </div>
  )
}

export default about

export const metadata = {                                   //can change dec and title according to the routes
  title: "ABOUT PAGE",
  description: "Generated by create next app",
};
